name: assignment-test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  full-test:
    runs-on: ubuntu-latest
    container:
      image: cuaesd/aesd-autotest:24-assignment4-buildroot
    timeout-minutes: 180

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up SSH for private access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Cache Buildroot downloads
        uses: actions/cache@v3
        with:
          path: buildroot/dl
          key: buildroot-dl-${{ runner.os }}-${{ hashFiles('buildroot/package/**') }}
          restore-keys: |
            buildroot-dl-

      - name: Run Buildroot and validation tests
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          FORCE_UNSAFE_CONFIGURE: 1
          BR2_JOBS: 2
        run: |
          echo "Starting full test..."
          export BR2_JOBS=2
          export FORCE_UNSAFE_CONFIGURE=1
          ./full-test.sh || (echo "Build failed, retrying..." && ./full-test.sh)

      - name: Cleanup SSH keys
        if: always()
        run: ssh-add -D
