name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
    full-test:
        container: cuaesd/aesd-autotest:24-assignment4-buildroot
        runs-on: self-hosted
        timeout-minutes: 120
        steps:
          - uses: actions/checkout@v2
          
          - name: Checkout submodules
            run: git submodule update --init --recursive
          
          - uses: webfactory/ssh-agent@v0.5.3
            with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          - name: Set environment and run test
            env:
              GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
            run: |
              export srctree=$(pwd)/base_external
              export BR2_EXTERNAL=$(pwd)/base_external
              ./full-test.sh
          
          - name: Cleanup
            if: always()
            run: ssh-add -D
