name: Assignment Test (Self-Hosted)

on:
  workflow_dispatch:
  push:
    branches: ["*"]
    tags-ignore: ["*"]

jobs:
  full-test:
    runs-on: self-hosted
    timeout-minutes: 180

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Show environment info
        run: |
          echo "Running on $(hostname)"
          uname -a
          df -h
          free -h

      - name: Set environment for Buildroot
        run: |
          echo "MAKEFLAGS=-j4" >> $GITHUB_ENV
          echo "BR2_JLEVEL=2" >> $GITHUB_ENV
          echo "FORCE_UNSAFE_CONFIGURE=1" >> $GITHUB_ENV

      - name: Run Buildroot full test
        run: |
          chmod +x full-test.sh
          ./full-test.sh

      - name: Upload Buildroot logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: buildroot-logs
          path: buildroot/output/build/* || true
