name: assignment-test

on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'

jobs:
  full-test:
    container: cuaesd/aesd-autotest:24-assignment4-buildroot
    runs-on: self-hosted
    timeout-minutes: 120

    steps:
      # ✅ Step 1: Checkout your repo
      - uses: actions/checkout@v2

      # ✅ Step 2: Set up SSH before submodules
      - name: Set up SSH for GitHub access
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # ✅ Step 3: Add GitHub to known hosts (prevents SSH verification failure)
      - name: Add GitHub to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      # ✅ Step 4: Now safely checkout submodules
      - name: Checkout submodules
        run: git submodule update --init --recursive

      # ✅ Step 5: Run your full test script
      - name: Run full test
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
        run: ./full-test.sh

      # ✅ Step 6: Cleanup SSH keys after job (good practice)
      - name: Cleanup
        if: always()
        run: ssh-add -D
