name: assignment-test

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  full-test:
    runs-on: ubuntu-latest     # ✅ GitHub-hosted runner
    container: cuaesd/aesd-autotest:24-assignment4-buildroot
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: Configure low-memory build
        run: |
          echo "Applying low-memory build configuration"
          export MAKEFLAGS="-j2"
          export BR2_JLEVEL=2

      - name: Run full test
        env:
          GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
          FORCE_UNSAFE_CONFIGURE: 1       # ✅ Fix for tar configure issue
        run: ./full-test.sh

      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up temporary files"
          rm -rf buildroot/output || true
